name: example
description: A simple command-line application.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.3
  hive: ^2.2.3
  path_provider: ^2.1.1
  json_annotation: ^4.8.1
  provider: ^6.0.5
  fast_sync_client:
    path: ../../fast_sync_client
  fast_sync_hive_dao:
    path: ../../fast_sync_hive_dao
  dio: ^5.3.3

dev_dependencies:
  pedantic: ^1.11.1
  build_runner: ^2.4.0
  json_serializable: ^6.7.1
  effective_dart: ^1.3.2
  lints: ^2.1.0
  hive_generator: ^2.0.1
