name: fast_sync_hive_dao
description: FastSync dart client to fastly sync your objects, without the need to use tones of apis
version: 1.0.3
homepage: https://github.com/Mahdibenamor/FastSync

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  path: ^1.8.3
  hive: ^2.2.3
  uuid: ^4.2.1
  fast_sync_client:
    path: ../fast_sync_client

dev_dependencies:
  build_runner: ^2.4.6
  hive_generator: ^2.0.0
  json_serializable: ^6.7.1
  lints: ^2.1.1
