name: fast_sync_floor_dao
description:
version: 1.0.0
homepage: https://github.com/Mahdibenamor/FastSync

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  json_annotation: ^4.8.1
  fast_sync_client:
    path: ../fast_sync_client

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  lints: ^2.1.1
