name: fast_sync_client
description: FastSync dart client to fastly sync your objects, without the need to use tones of apis
version: 1.0.0
homepage: https://github.com/Mahdibenamor/FastSync

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  uuid: ^4.1.0

dev_dependencies:
  lints: ^2.1.1
