name: fast_sync_client
description:
version: 1.0.0
homepage: https://github.com/Mahdibenamor/FastSync

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  get_it: ^7.6.4

dev_dependencies:
  lints: ^2.1.1
